### PR TITLE
Update bt_ci_workflow_unit_tests.yml commit when no change in badges

### PR DESCRIPTION
**Pull request by BT-tkarpinski**

### CODE REVIEW

**Comment by BT-tkarpinski** [comment]
Tested @BT-rmartin 
https://github.com/brain-tec/reidl/commit/25ab64a9777446b14186ee824a869881c0dc815a
https://github.com/brain-tec/reidl/actions/runs/4787050126/jobs/8511768792

**Comment by BT-tkarpinski** [comment]
@BT-rmartin 
New tests
https://github.com/brain-tec/reidl/actions/runs/4787879545/jobs/8513723135
https://github.com/brain-tec/reidl/pull/533/files

**Comment by BT-tkarpinski** [comment]
@BT-rmartin https://github.com/brain-tec/reidl/actions/runs/4788096266/jobs/8514224924

**Review by BT-rmartin — CHANGES_REQUESTED** [review]
**[question]** After adding the check of git status, can't we remove the allow-empty?

**Review by BT-rmartin — APPROVED** [review]

**Pull request merged**
